In [ ]:
# 1.2 Dataset Understanding

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

pd.set_option("display.width", 120)

Libraries imported successfully.

In [5]:
# Load Raw Dataset

DATA_PATH = "diabetic_data.csv"

df = pd.read_csv(
    DATA_PATH,
    na_values=["?"]
)

print("Dataset loaded successfully.")

Dataset loaded successfully.

C:\Users\368435\AppData\Local\Temp\ipykernel_21196\3509576147.py:5: DtypeWarning: Columns (0: payer_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [6]:
# Dataset dimensions

rows, columns = df.shape

print("Number of rows      :", rows)
print("Number of columns   :", columns)

Number of rows      : 101766
Number of columns   : 50

In [7]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

01. encounter_id
02. patient_nbr
03. race
04. gender
05. age
06. weight
07. admission_type_id
08. discharge_disposition_id
09. admission_source_id
10. time_in_hospital
11. payer_code
12. medical_specialty
13. num_lab_procedures
14. num_procedures
15. num_medications
16. number_outpatient
17. number_emergency
18. number_inpatient
19. diag_1
20. diag_2
21. diag_3
22. number_diagnoses
23. max_glu_serum
24. A1Cresult
25. metformin
26. repaglinide
27. nateglinide
28. chlorpropamide
29. glimepiride
30. acetohexamide
31. glipizide
32. glyburide
33. tolbutamide
34. pioglitazone
35. rosiglitazone
36. acarbose
37. miglitol
38. troglitazone
39. tolazamide
40. examide
41. citoglipton
42. insulin
43. glyburide-metformin
44. glipizide-metformin
45. glimepiride-pioglitazone
46. metformin-rosiglitazone
47. metformin-pioglitazone
48. change
49. diabetesMed
50. readmitted

In [8]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      99493 non-null   str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    3197 non-null    str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                61510 non-null   str
 11  medical_specialty         51817 non-null   str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101745 non-null  str
 19  diag_2                    101408 non-null  str
 20  diag_3                    100343 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [10]:
# Number of unique hospital encounters

unique_encounters = df["encounter_id"].nunique()

print("Total rows       :", len(df))
print("Unique encounters:", unique_encounters)

Total rows       : 101766
Unique encounters: 101766

In [11]:
# Number of unique patients

unique_patients = df["patient_nbr"].nunique()

print("Total encounters:", len(df))
print("Unique patients  :", unique_patients)

Total encounters: 101766
Unique patients  : 71518

In [12]:
# Number of encounters per patient

encounters_per_patient = df["patient_nbr"].value_counts()

print("Patients with exactly 1 encounter:",
      (encounters_per_patient == 1).sum())

print("Patients with more than 1 encounter:",
      (encounters_per_patient > 1).sum())

print("\nMaximum encounters for one patient:",
      encounters_per_patient.max())

Patients with exactly 1 encounter: 54745
Patients with more than 1 encounter: 16773

Maximum encounters for one patient: 40

In [13]:
# Show the distribution of number of encounters per patient

encounters_per_patient.value_counts().sort_index()

count
1     54745
2     10434
3      3328
4      1421
5       717
6       346
7       207
8       111
9        70
10       42
11       20
12       19
13       14
14        5
15        9
16        4
17        3
18        6
19        3
20        6
21        1
22        2
23        3
28        1
40        1
Name: count, dtype: int64

In [14]:
# Original readmission target distribution

readmission_counts = df["readmitted"].value_counts()

print(readmission_counts)

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [15]:
# Original target distribution in percentage

readmission_percentage = (
    df["readmitted"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(readmission_percentage)

readmitted
NO     53.91
>30    34.93
<30    11.16
Name: proportion, dtype: float64

In [16]:

# Binary Target Derivation

df["target"] = (
    df["readmitted"] == "<30"
).astype(int)

print("Binary target created successfully.")

Binary target created successfully.

In [17]:
# Binary target counts

target_counts = df["target"].value_counts().sort_index()

print(target_counts)

target
0    90409
1    11357
Name: count, dtype: int64

In [18]:
# Binary target percentages

target_percentage = (
    df["target"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print(target_percentage)

target
0    88.84
1    11.16
Name: proportion, dtype: float64

In [19]:
# Display data type for every feature

feature_dtypes = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str).values
})

feature_dtypes

                     feature  dtype
0               encounter_id  int64
1                patient_nbr  int64
2                       race    str
3                     gender    str
4                        age    str
5                     weight    str
6          admission_type_id  int64
7   discharge_disposition_id  int64
8        admission_source_id  int64
9           time_in_hospital  int64
10                payer_code    str
11         medical_specialty    str
12        num_lab_procedures  int64
13            num_procedures  int64
14           num_medications  int64
15         number_outpatient  int64
16          number_emergency  int64
17          number_inpatient  int64
18                    diag_1    str
19                    diag_2    str
20                    diag_3    str
21          number_diagnoses  int64
22             max_glu_serum    str
23                 A1Cresult    str
24                 metformin    str
25               repaglinide    str
26               nateglinide    str
27            chlorpropamide    str
28               glimepiride    str
29             acetohexamide    str
30                 glipizide    str
31                 glyburide    str
32               tolbutamide    str
33              pioglitazone    str
34             rosiglitazone    str
35                  acarbose    str
36                  miglitol    str
37              troglitazone    str
38                tolazamide    str
39                   examide    str
40               citoglipton    str
41                   insulin    str
42       glyburide-metformin    str
43       glipizide-metformin    str
44  glimepiride-pioglitazone    str
45   metformin-rosiglitazone    str
46    metformin-pioglitazone    str
47                    change    str
48               diabetesMed    str
49                readmitted    str
50                    target  int64

In [20]:
# Count columns by pandas data type

df.dtypes.value_counts()

str      37
int64    14
Name: count, dtype: int64

In [21]:
# Unique values for every column

unique_summary = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "unique_values": [
        df[col].nunique(dropna=True)
        for col in df.columns
    ]
})

unique_summary

                     feature  dtype  unique_values
0               encounter_id  int64         101766
1                patient_nbr  int64          71518
2                       race    str              5
3                     gender    str              3
4                        age    str             10
5                     weight    str              9
6          admission_type_id  int64              8
7   discharge_disposition_id  int64             26
8        admission_source_id  int64             17
9           time_in_hospital  int64             14
10                payer_code    str             17
11         medical_specialty    str             72
12        num_lab_procedures  int64            118
13            num_procedures  int64              7
14           num_medications  int64             75
15         number_outpatient  int64             39
16          number_emergency  int64             33
17          number_inpatient  int64             21
18                    diag_1    str            716
19                    diag_2    str            748
20                    diag_3    str            789
21          number_diagnoses  int64             16
22             max_glu_serum    str              3
23                 A1Cresult    str              3
24                 metformin    str              4
25               repaglinide    str              4
26               nateglinide    str              4
27            chlorpropamide    str              4
28               glimepiride    str              4
29             acetohexamide    str              2
30                 glipizide    str              4
31                 glyburide    str              4
32               tolbutamide    str              2
33              pioglitazone    str              4
34             rosiglitazone    str              4
35                  acarbose    str              4
36                  miglitol    str              4
37              troglitazone    str              2
38                tolazamide    str              3
39                   examide    str              1
40               citoglipton    str              1
41                   insulin    str              4
42       glyburide-metformin    str              4
43       glipizide-metformin    str              2
44  glimepiride-pioglitazone    str              2
45   metformin-rosiglitazone    str              2
46    metformin-pioglitazone    str              2
47                    change    str              2
48               diabetesMed    str              2
49                readmitted    str              3
50                    target  int64              2

In [22]:

# Missing Value Analysis

missing_count = df.isna().sum()

missing_percentage = (
    df.isna().mean() * 100
).round(2)

missing_summary = pd.DataFrame({
    "feature": df.columns,
    "missing_count": missing_count.values,
    "missing_percentage": missing_percentage.values
})

missing_summary = (
    missing_summary
    .sort_values(
        by="missing_percentage",
        ascending=False
    )
    .reset_index(drop=True)
)

missing_summary

                     feature  missing_count  missing_percentage
0                     weight          98569               96.86
1              max_glu_serum          96420               94.75
2                  A1Cresult          84748               83.28
3          medical_specialty          49949               49.08
4                 payer_code          40256               39.56
5                       race           2273                2.23
6                     diag_3           1423                1.40
7                     diag_2            358                0.35
8                     diag_1             21                0.02
9                patient_nbr              0                0.00
10              encounter_id              0                0.00
11          time_in_hospital              0                0.00
12       admission_source_id              0                0.00
13            num_procedures              0                0.00
14        num_lab_procedures              0                0.00
15         admission_type_id              0                0.00
16  discharge_disposition_id              0                0.00
17                       age              0                0.00
18                    gender              0                0.00
19          number_inpatient              0                0.00
20          number_emergency              0                0.00
21         number_outpatient              0                0.00
22           num_medications              0                0.00
23          number_diagnoses              0                0.00
24                 metformin              0                0.00
25               repaglinide              0                0.00
26               nateglinide              0                0.00
27            chlorpropamide              0                0.00
28               glimepiride              0                0.00
29             acetohexamide              0                0.00
30                 glipizide              0                0.00
31                 glyburide              0                0.00
32               tolbutamide              0                0.00
33              pioglitazone              0                0.00
34             rosiglitazone              0                0.00
35                  acarbose              0                0.00
36                  miglitol              0                0.00
37              troglitazone              0                0.00
38                tolazamide              0                0.00
39                   examide              0                0.00
40               citoglipton              0                0.00
41                   insulin              0                0.00
42       glyburide-metformin              0                0.00
43       glipizide-metformin              0                0.00
44  glimepiride-pioglitazone              0                0.00
45   metformin-rosiglitazone              0                0.00
46    metformin-pioglitazone              0                0.00
47                    change              0                0.00
48               diabetesMed              0                0.00
49                readmitted              0                0.00
50                    target              0                0.00

In [23]:
# Features containing missing values

missing_features = missing_summary[
    missing_summary["missing_count"] > 0
]

missing_features

             feature  missing_count  missing_percentage
0             weight          98569               96.86
1      max_glu_serum          96420               94.75
2          A1Cresult          84748               83.28
3  medical_specialty          49949               49.08
4         payer_code          40256               39.56
5               race           2273                2.23
6             diag_3           1423                1.40
7             diag_2            358                0.35
8             diag_1             21                0.02

In [24]:
# Overall missing-value summary

total_cells = df.shape[0] * df.shape[1]
total_missing = df.isna().sum().sum()

print("Total cells          :", total_cells)
print("Total missing values :", total_missing)
print(
    "Overall missing %    :",
    round((total_missing / total_cells) * 100, 2)
)

Total cells          : 5190066
Total missing values : 374017
Overall missing %    : 7.21

In [25]:
# Top 10 features with highest missing percentage

missing_summary.head(10)

             feature  missing_count  missing_percentage
0             weight          98569               96.86
1      max_glu_serum          96420               94.75
2          A1Cresult          84748               83.28
3  medical_specialty          49949               49.08
4         payer_code          40256               39.56
5               race           2273                2.23
6             diag_3           1423                1.40
7             diag_2            358                0.35
8             diag_1             21                0.02
9        patient_nbr              0                0.00